### ISSUE TITLE
Request for addition

### ISSUE THREAD

**Issue by numeredev** [MooersLab/Curve-fitting-software#1]
Hi!

May we kindly as that you consider to add NumeRe (https://en.numere.org) to your list of curve fitting tools, especially as it provides curve fitting, data analysis and numerical calculation alltogether in a single application. It's freely available and open source (GPLv3).

Please get in touch, if you have further questions. Thanks for your consideration.

**Comment by MooersLab** [comment]
Your request has been fulfilled. I am closing this issue now.

**Comment by numeredev** [comment]
Thanks for considering the addition. Just a little wish: you have a typo in our applications name. Instead of NumeRe you wrote NumerRe.

**Comment by MooersLab** [comment]
Thank you for pointing out the typo! It is fixed now.
